import { GetStaticProps } from 'next';
import Head from 'next/head';
import { getSortedPostsData } from '../lib/posts';
import homeStyles from '../styles/Home.module.css';

const Home = ({
  allPostsData,
}: {
  allPostsData: { date: string; title: string; id: string }[];
}) => {
  return (
    <div>
      <Head>
        <title>Title</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={homeStyles.headingMd}>
        <p>Hello</p>
        <p>introduction</p>
      </section>
      <section className={`${homeStyles.headingMd} ${homeStyles.padding1px}`}>
        <h2 className={homeStyles.headingLg}>Blog</h2>
        <ul className={homeStyles.list}>
          {allPostsData.map(({ id, title, date }) => (
            <li className={homeStyles.listItem} key={id}>
              <a>{title}</a>
              <br />
              <p>{date}</p>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
};
