import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { getSortedPostsData } from '../lib/posts';
import homeStyles from '../styles/Home.module.css';

const Home = ({
  allPostsData,
}: {
  allPostsData: { date: string; title: string; id: string }[];
}) => {
  return (
    <div className={`${homeStyles.container}`}>
      <div>
        <Head>
          <title>NextJs-Tutorial-Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section>
          <h1 className={`${homeStyles.headingLg}`}>Hello, I&apos; sukyung</h1>
          <p className={`${homeStyles.text}`}>
            This is a Next.js website -{' '}
            <a href="https://github.com/sukyungdev/Next.js-tutorial-blog">Github repository</a>
            <br />
            <a href="https://nextjs.org/learn/foundations/about-nextjs">Next.js tutorial</a>
          </p>
        </section>
        <section>
          <h2>Blog</h2>
          <ul className={`${homeStyles.list}`}>
            {allPostsData.map(({ id, title, date }) => (
              <li key={id} className={`${homeStyles.postBox}`}>
                <Link href={`posts/${id}`}>
                  <h2 className={`${homeStyles.postName}`}>{title}</h2>
                </Link>
                <p className={`${homeStyles.date}`}>{date}</p>
              </li>
            ))}
          </ul>
        </section>
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
};
